### ISSUE TITLE
[Feature Request] Show the 6-digit token as QR

### ISSUE THREAD

**Issue by ozett** [qoomon/otp-authenticator-webapp#30]
Would be a great feature not only to show the OTP-URL as QR-Code, but
instead to show the 6-digits as a QR.

That way i could use my phone before a QR-Scanner 
and must not key-in the digits.

besides this, great peace of art.
pretty clean gui,
👍 

(and i like the clock and admire the ponies on your homepage!)

**Comment by qoomon** [comment]
thanks dude ☺️

Surry but I don't get your feature request or your workflow. Sure it would be easy to display the digits as QR code.

My understanding of your workflow is as follows, is that right?:
* open a QR scanner app on your phone
* scan the 6 digits QR code
* copy the 6 digits
* open the app that is requesting the 6 digits
* paste the 6 digits

**Comment by ozett** [comment]
my workflow is slightly different.
and your code seems a great solution to it.

i have a RFID reader on my doors to open them.
logic is made with node-red. works now for years.

i have also a QR scanner on my door,
but to make QR codes safe(r) against replay attacks, the OTP mechanism is great.
with your code i can make an alternative to an (un?)trusted app like google authenticator.
AND as a great benefit, i could show the 6-digit totpassword as an QR-code to the reader.
only some readers are capable to read from phone screens, i have one. and they are cheap.

your code could be a central piece in this.

(have to figure out how to run it offline,. and as i am no developer, still in doubt if a cookie with the secret would be safe. but as fas as i read, ie. chrome encrypts the cookie storage, so at least i would be safe enought..

more infos?

**Comment by qoomon** [comment]
I see, however I'm not planning to store the secrets in a cookie or local storage.

**Comment by ozett** [comment]
yeah, storing the secrets somewhere could be my solution.
as for security conerns in comparision to some uses of RFID there is no big differences.
and in comparison to normal door-locks, it is a lot more secure and a lot more flexible.

most things must be used, to see how design can change and goals are reached or changed.
i love how the gui is made. seems to be a clean style like on most of your other projects
👍

**Comment by qoomon** [comment]
A qr button at the right of the 6-Digits would be an option. A click should open a overlay with the qr code I think.
However I don't have the time to do so. Any PR would be welcome

**Comment by ozett** [comment]
looks like somone else build a device like this.
https://www.token2.com/shop/product/molto-2-v2-multi-profile-totp-programmable-hardware-token

i am unexperienced in coding, think i am not capable of doing a PR,
but i am willing to look what i can bring in...
