### ISSUE TITLE
CodeQL: All jobs have failed

### ISSUE THREAD

**Issue by krishnastunning** [qoomon/otp-authenticator-webapp#37]
please fix this error i think it database error "CodeQL: All jobs have failed"

**Comment by qoomon** [comment]
Thanks for reporting, however this is the worst bug report ever.

Where does this error occurs? Form what I can see everything works as expected all actions are green and the page is online and running.

**Comment by krishnastunning** [comment]
Actually, I don't see that our database is working. It does not save any data that we have used to generate.

**Comment by qoomon** [comment]
I do not understand what you are talking about.

**Comment by krishnastunning** [comment]
can you try to save data on your site becz I belive that it does not save data

**Comment by qoomon** [comment]
Still I have no idea what you want to tell me
