### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by CraftedCat** [qoomon/otp-authenticator-webapp#4]
After fork, app not available. What i need to do?)

**Comment by qoomon** [comment]
Please check if Your Repository -> Settings -> GitHub Pages -> Source is set to 'gh-pages'
there you should also see a note like " √ Your site is published at https://USERNAME.github.io/otp-authenticator-webapp/"

**Comment by CraftedCat** [comment]
Thanks!

**Comment by ozett** [comment]
tryed to fork today and make the app working.
youre readme.md is a bit to short, 
as i noob i found two steps missing:

1) fork all branches (un-click the default)
2) set pages to `gh-pages` and (!) `docs`

| step 1|
|:---:|
![image](https://user-images.githubusercontent.com/5937811/211796952-201a5d07-76f8-4c1b-80c4-c3313de08388.png)
|step 2|
![image](https://user-images.githubusercontent.com/5937811/211797165-85438952-4867-43fc-9eef-a60d870121f1.png)
