### ISSUE TITLE
Pasting OTP secret doesn't work any more

### ISSUE THREAD

**Issue by kiriakos** [qoomon/otp-authenticator-webapp#8]
Going to https://qoomon.github.io/otp-authenticator-webapp/ and pasting a secret produces an `Invalid Secret!` message.

Console says:
```
TypeError: "r is not a constructor"
    getToken https://qoomon.github.io/otp-authenticator-webapp/main.js:1
    w https://qoomon.github.io/otp-authenticator-webapp/main.js:1
    <anonymous> https://qoomon.github.io/otp-authenticator-webapp/main.js:1
    <anonymous> https://qoomon.github.io/otp-authenticator-webapp/main.js:1
```

**Comment by qoomon** [comment]
oh thanks for reporting, I've updated dependencies yesterday.
I will investigate

**Comment by qoomon** [comment]
It's working again. It was caused by the `progressbar.js` lib. I replaced id with my own implementation. 

minus one dependency, yeahy :-D
